import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FileText, Wand2, Languages, FileCheck, Copy, Download, RefreshCw } from 'lucide-react';
import { policies } from '../data/policies';
import './DocumentGenerator.css';

type ToolType = 'generate' | 'summarize' | 'translate';

export const DocumentGenerator = () => {
    const [activeTool, setActiveTool] = useState<ToolType>('generate');
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [result, setResult] = useState<string | null>(null);

    // Generation State
    const [genData, setGenData] = useState({
        template: 'offer-letter',
        candidateName: '',
        role: '',
        startDate: '',
        ctc: ''
    });

    // Summarization/Translation State
    const [selectedPolicyId, setSelectedPolicyId] = useState('');
    const [targetLang, setTargetLang] = useState('es');

    const handleGenerate = async () => {
        setError(null);
        setResult(null);

        // Validation
        if (!genData.candidateName.trim()) {
            setError('Please enter the candidate name.');
            return;
        }
        if (!genData.role.trim()) {
            setError('Please enter the role title.');
            return;
        }

        if (genData.template === 'offer-letter') {
            if (!genData.ctc.trim()) {
                setError('Please enter the Annual CTC.');
                return;
            }
            if (!genData.startDate) {
                setError('Please select a start date.');
                return;
            }
        }

        setIsLoading(true);

        // Simulate AI delay
        await new Promise(resolve => setTimeout(resolve, 2000));

        let generatedContent = '';
        if (genData.template === 'offer-letter') {
            generatedContent = `# PRIVATE & CONFIDENTIAL\n\nDate: ${new Date().toLocaleDateString()}\n\nDear **${genData.candidateName || '[Candidate Name]'}**,\n\nWe are pleased to offer you the position of **${genData.role || '[Role]'}** at HRMS Corp. We believe your skills and experience will be an ideal fit for our creative team.\n\n**Compensation Package**\nYour annual Cost to Company (CTC) will be **${genData.ctc || '[Amount]'}**, structured as per the company policy.\n\n**Start Date**\nWe look forward to welcoming you on **${genData.startDate || '[Date]'}**.\n\nPlease sign and return the duplicate copy of this letter as a token of your acceptance.\n\nSincerely,\n\nHR Director\nHRMS Corp`;
        } else {
            generatedContent = `# NON-DISCLOSURE AGREEMENT\n\nThis Agreement is made on ${new Date().toLocaleDateString()}.\n\n**BETWEEN:**\nHRMS Corp (The "Company")\n\n**AND:**\n${genData.candidateName || '[Name]'} (The "Recipient")\n\n1. **Confidential Information**\nThe Recipient agrees to keep all proprietary information confidential and shall not disclose it to any third party without prior written consent.\n\n2. **Term**\nThis agreement shall remain in effect for a period of 2 years from the date of signing.`;
        }

        setResult(generatedContent);
        setIsLoading(false);
    };

    const handleSummarize = async () => {
        if (!selectedPolicyId) return;
        setIsLoading(true);
        setResult(null);
        await new Promise(resolve => setTimeout(resolve, 1500));

        const policy = policies.find(p => p.id === selectedPolicyId);
        if (policy) {
            setResult(`### ✨ AI Summary: ${policy.title}\n\n**Core Point:**\n${policy.content.split('.')[0]}.\n\n**Key Takeaways:**\n• Applies to all full-time employees.\n• Requires manager approval.\n• Subject to annual review.\n\n*> This summary was generated by HRMS AI to help you grasp the key details quickly.*`);
        }
        setIsLoading(false);
    };

    const handleTranslate = async () => {
        if (!selectedPolicyId) return;
        setIsLoading(true);
        setResult(null);
        await new Promise(resolve => setTimeout(resolve, 1800));

        const policy = policies.find(p => p.id === selectedPolicyId);
        const langMap: Record<string, string> = { 'es': 'Spanish', 'fr': 'French', 'hi': 'Hindi', 'de': 'German' };

        if (policy) {
            let translatedText = '';
            // Mock translations
            if (targetLang === 'es') translatedText = `(Translated to Spanish)\n\n**${policy.title}**\n\n${policy.content}\n\n*Condiciones:*\n• No transferible\n• Requiere aprobación`;
            else if (targetLang === 'hi') translatedText = `(Translated to Hindi)\n\n**${policy.title}**\n\n${policy.content}\n\n*शर्ते:* \n• केवल पूर्णकालिक कर्मचारियों के लिए\n• प्रबंधक की मंजूरी अनिवार्य है`;
            else translatedText = `(Translated to ${langMap[targetLang]})\n\n[Simulated Translation of ${policy.title}]\n\n${policy.content}`;

            setResult(translatedText);
        }
        setIsLoading(false);
    };

    return (
        <div className="doc-gen-container">
            <header className="doc-header">
                <div className="header-icon-bg">
                    <Wand2 size={24} color="white" />
                </div>
                <div>
                    <h2>AI Document Assistant</h2>
                    <p>Generate, summarize, and translate HR documents instantly.</p>
                </div>
            </header>

            <div className="tools-tabs">
                <button
                    className={`tab-btn ${activeTool === 'generate' ? 'active' : ''}`}
                    onClick={() => { setActiveTool('generate'); setResult(null); }}
                >
                    <FileCheck size={18} /> Generate
                </button>
                <button
                    className={`tab-btn ${activeTool === 'summarize' ? 'active' : ''}`}
                    onClick={() => { setActiveTool('summarize'); setResult(null); }}
                >
                    <FileText size={18} /> Summarize
                </button>
                <button
                    className={`tab-btn ${activeTool === 'translate' ? 'active' : ''}`}
                    onClick={() => { setActiveTool('translate'); setResult(null); }}
                >
                    <Languages size={18} /> Translate
                </button>
            </div>

            <div className="tool-content glass-effect">
                <div className="input-section">
                    <AnimatePresence mode="wait">
                        {activeTool === 'generate' && (
                            <motion.div
                                initial={{ opacity: 0, x: -20 }}
                                animate={{ opacity: 1, x: 0 }}
                                exit={{ opacity: 0, x: 20 }}
                                className="form-grid"
                                key="gen-form"
                            >
                                <div className="form-group">
                                    <label>Template Type</label>
                                    <select
                                        value={genData.template}
                                        onChange={e => setGenData({ ...genData, template: e.target.value })}
                                    >
                                        <option value="offer-letter">Offer Letter</option>
                                        <option value="nda">NDA Contract</option>
                                    </select>
                                </div>
                                <div className="form-group">
                                    <label>Candidate Name</label>
                                    <input
                                        type="text"
                                        placeholder="ex. Jane Smith"
                                        value={genData.candidateName}
                                        onChange={e => setGenData({ ...genData, candidateName: e.target.value })}
                                    />
                                </div>
                                <div className="form-group">
                                    <label>Role Title</label>
                                    <input
                                        type="text"
                                        placeholder="ex. Senior Developer"
                                        value={genData.role}
                                        onChange={e => setGenData({ ...genData, role: e.target.value })}
                                    />
                                </div>
                                {genData.template === 'offer-letter' && (
                                    <>
                                        <div className="form-group">
                                            <label>Annual CTC</label>
                                            <input
                                                type="text"
                                                placeholder="ex. $120,000"
                                                value={genData.ctc}
                                                onChange={e => setGenData({ ...genData, ctc: e.target.value })}
                                            />
                                        </div>
                                        <div className="form-group">
                                            <label>Start Date</label>
                                            <input
                                                type="date"
                                                value={genData.startDate}
                                                onChange={e => setGenData({ ...genData, startDate: e.target.value })}
                                            />
                                        </div>
                                    </>
                                )}

                                {error && (
                                    <motion.div
                                        initial={{ opacity: 0, scale: 0.95 }}
                                        animate={{ opacity: 1, scale: 1 }}
                                        className="error-message"
                                        style={{ color: '#ef4444', fontSize: '13px', padding: '8px', background: 'rgba(239,68,68,0.1)', borderRadius: '8px', textAlign: 'center' }}
                                    >
                                        {error}
                                    </motion.div>
                                )}

                                <button className="action-btn" onClick={handleGenerate} disabled={isLoading}>
                                    {isLoading ? <RefreshCw className="spin" size={20} /> : <Wand2 size={20} />}
                                    {isLoading ? 'Generating...' : 'Generate Document'}
                                </button>
                            </motion.div>
                        )}

                        {activeTool === 'summarize' && (
                            <motion.div
                                initial={{ opacity: 0, x: -20 }}
                                animate={{ opacity: 1, x: 0 }}
                                exit={{ opacity: 0, x: 20 }}
                                className="form-stack"
                                key="sum-form"
                            >
                                <div className="form-group">
                                    <label>Select Policy to Summarize</label>
                                    <select
                                        value={selectedPolicyId}
                                        onChange={e => setSelectedPolicyId(e.target.value)}
                                    >
                                        <option value="">-- Choose a Policy --</option>
                                        {policies.map(p => (
                                            <option key={p.id} value={p.id}>{p.title}</option>
                                        ))}
                                    </select>
                                </div>
                                <button
                                    className="action-btn"
                                    onClick={handleSummarize}
                                    disabled={!selectedPolicyId || isLoading}
                                >
                                    {isLoading ? <RefreshCw className="spin" size={20} /> : <FileText size={20} />}
                                    {isLoading ? 'Analyzing...' : 'Summarize Policy'}
                                </button>
                            </motion.div>
                        )}

                        {activeTool === 'translate' && (
                            <motion.div
                                initial={{ opacity: 0, x: -20 }}
                                animate={{ opacity: 1, x: 0 }}
                                exit={{ opacity: 0, x: 20 }}
                                className="form-stack"
                                key="trans-form"
                            >
                                <div className="form-group">
                                    <label>Select Policy</label>
                                    <select
                                        value={selectedPolicyId}
                                        onChange={e => setSelectedPolicyId(e.target.value)}
                                    >
                                        <option value="">-- Choose a Policy --</option>
                                        {policies.map(p => (
                                            <option key={p.id} value={p.id}>{p.title}</option>
                                        ))}
                                    </select>
                                </div>
                                <div className="form-group">
                                    <label>Target Language</label>
                                    <select
                                        value={targetLang}
                                        onChange={e => setTargetLang(e.target.value)}
                                    >
                                        <option value="es">Spanish (Español)</option>
                                        <option value="fr">French (Français)</option>
                                        <option value="de">German (Deutsch)</option>
                                        <option value="hi">Hindi (हिंदी)</option>
                                    </select>
                                </div>
                                <button
                                    className="action-btn"
                                    onClick={handleTranslate}
                                    disabled={!selectedPolicyId || isLoading}
                                >
                                    {isLoading ? <RefreshCw className="spin" size={20} /> : <Languages size={20} />}
                                    {isLoading ? 'Translating...' : 'Translate Document'}
                                </button>
                            </motion.div>
                        )}
                    </AnimatePresence>
                </div>

                <div className="preview-section">
                    <div className="preview-header">
                        <span>LIVE PREVIEW</span>
                        {result && (
                            <div className="preview-actions">
                                <button title="Copy"><Copy size={16} /></button>
                                <button title="Download"><Download size={16} /></button>
                            </div>
                        )}
                    </div>
                    <div className="preview-content">
                        {isLoading ? (
                            <div className="loading-state">
                                <div className="ai-pulse"></div>
                                <p>AI is processing your request...</p>
                            </div>
                        ) : result ? (
                            <motion.div
                                initial={{ opacity: 0 }}
                                animate={{ opacity: 1 }}
                                className="markdown-body"
                            >
                                {result.split('\n').map((line, i) => (
                                    <p key={i} className={line.startsWith('#') ? 'heading' : ''}>
                                        {line.replace(/#/g, '').trim()}
                                    </p>
                                ))}
                            </motion.div>
                        ) : (
                            <div className="empty-state">
                                <Wand2 size={48} opacity={0.2} />
                                <p>Select a tool and enter details to generate content.</p>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
};
